### ISSUE TITLE
Fonts doesn't get copied and errors out

### ISSUE THREAD

**Issue by akshaybabloo** [laynezh/vite-plugin-lib-assets#57]
Here is the plugin configuration:

```js
plugins: [
    libAssetsPlugin({
        limit: 1024 * 8,
        extensions: ['.otf', '.ttf', '.woff', '.woff2'],
        outputPath: 'static/fonts',
    }),
],
```

But I also have a custom output and it looks like:

```js
rollupOptions: {
    output: {
        assetFileNames: (assetInfo) => {
            let extType = assetInfo.name.split('.').at(1);
            if (/png|jpe?g|svg|gif|tiff|bmp|ico/i.test(extType)) {
                extType = 'img';
            } else if (/woff|woff2/.test(extType)) {
                extType = "css";
            }
            if (assetInfo.name === 'style.css') return 'css/main.css';
            return `${extType}/[name][extname]`;
        },
        chunkFileNames: 'js/[name].[format].js',
        entryFileNames: 'js/[name].[format].js',
    }
}
```

When I try to build it, I get the following error:

```
[commonjs--resolver] Could not set source for asset "static/fonts/[contenthash].woff2", asset source needs to be a string, Uint8Array or Buffer.
error during build:
RollupError: Could not set source for asset "static/fonts/[contenthash].woff2", asset source needs to be a string, Uint8Array or Buffer.
    at error (file:///home/akshay/code/personal/gollahalli.com/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at getValidSource (file:///home/akshay/code/personal/gollahalli.com/node_modules/rollup/dist/es/shared/node-entry.js:18113:16)
    at FileEmitter.emitAsset (file:///home/akshay/code/personal/gollahalli.com/node_modules/rollup/dist/es/shared/node-entry.js:18274:15)
    at FileEmitter.emitFile (file:///home/akshay/code/personal/gollahalli.com/node_modules/rollup/dist/es/shared/node-entry.js:18153:25)
    at emitFile (file:///home/akshay/code/personal/gollahalli.com/node_modules/@laynezh/vite-plugin-lib-assets/dist/index.js:219:15)
    at file:///home/akshay/code/personal/gollahalli.com/node_modules/@laynezh/vite-plugin-lib-assets/dist/index.js:329:27
    at Array.forEach (<anonymous>)
    at Object.resolveId (file:///home/akshay/code/personal/gollahalli.com/node_modules/@laynezh/vite-plugin-lib-assets/dist/index.js:328:21)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/akshay/code/personal/gollahalli.com/node_modules/rollup/dist/es/shared/node-entry.js:18542:28)
    at async resolveId (file:///home/akshay/code/personal/gollahalli.com/node_modules/rollup/dist/es/shared/node-entry.js:17211:26)
```

Not sure what this error is. Complete configuration can be found at - https://github.com/akshaybabloo/spark-hugo-theme/blob/spark-2/vite.config.mts

**Comment by coder-layne** [comment]
@akshaybabloo Thanks for your feedback. I can't get enough information from the error message to identify the source of the exception. Can you provide a minimal reproducible version?

**Comment by akshaybabloo** [comment]
Sorry I think I found the issue. I might have found another issue, I will open a new ticket for that. Thank you!
